import 'package:noviagen/features/gallery/controllers/pending_media_refresh_controller.dart';

typedef PendingMediaRefreshDependencies = PendingMediaRefreshControllerDependencies;
typedef PendingMediaRefresh = PendingMediaRefreshController;
